// This file was automatically generated by the Soy compiler.
// Please don't edit this file by hand.
// source: src/__tests__/fixtures/simple/index.soy

/**
 * @fileoverview Templates in namespace soy.examples.simple.
 * @suppress {suspiciousCode}
 * @suppress {uselessCode}
 * @suppress {strictMissingProperties} TODO(b/214874268): Remove strictMissingProperties suppression after b/214427036 is fixed
 * @public
 */

goog.provide('soy.examples.simple');
goog.require('goog.soy');
goog.requireType('goog.soy.data.SanitizedHtml');
goog.require('soy');

/**
 * @param {?Object<string, *>=} opt_data
 * @param {(?goog.soy.IjData|?Object<string, *>)=} opt_ijData
 * @return {!goog.soy.data.SanitizedHtml}
 * @suppress {checkTypes}
 */
soy.examples.simple.helloWorld = function (opt_data, opt_ijData) {
  const $ijData = /** @type {!goog.soy.IjData} */opt_ijData;
  if (goog.soy.shouldStub && goog.soy.shouldStubAtRuntime() && soy.examples.simple.helloWorld_soyInternalStubs) {
    return soy.examples.simple.helloWorld_soyInternalStubs(opt_data, $ijData);
  }
  if (goog.DEBUG && soy.$$stubsMap['soy.examples.simple.helloWorld']) {
    return soy.$$stubsMap['soy.examples.simple.helloWorld'](opt_data, $ijData);
  }
  return soy.VERY_UNSAFE.ordainSanitizedHtml('Hello world!');
};
if (false) {
  /**
   * @param {!Object} $$areYouAnInternalCaller
   * @param {!goog.soy.IjData} $ijData
   * @return {!goog.soy.data.SanitizedHtml}
   * @suppress {checkTypes}
   */
  soy.examples.simple.helloWorld_soyInternalStubs;
}
if (goog.DEBUG) {
  /**
   * @nocollapse
   * @type {string}
   */
  soy.examples.simple.helloWorld.soyTemplateName = 'soy.examples.simple.helloWorld';
}