import {
  type TransformOptions,
  transformSync as babelTransformSync,
} from "@babel/core";

export const basicSoyString = `{namespace soy.examples.simple}

{template helloWorld}
  {msg desc="Says hello to the world."}
    Hello world!
  {/msg}
{/template}`;

export function wasGeneratedBySoyCompiler(code: string): boolean {
  return code.startsWith(
    "// This file was automatically generated by the Soy compiler.",
  );
}

export function transform(
  code: string,
  filename: null | string,
  options: Omit<TransformOptions, "babelrc" | "configFile" | "parserOpts">,
): string {
  const res = babelTransformSync(code, {
    ...options,
    babelrc: false,
    configFile: false,
    parserOpts: {
      sourceFilename: filename ?? undefined,
    },
  });

  return res?.code as string;
}
